server:
  port: 80

spring:
  application:
    name:  cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    # 表示是否将自己注册进EurekaService默认为true
    register-with-eureka: true
    # 是否从EurekaService抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80  #服务名称修改
    prefer-ip-address: true #显示ip
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超过将剔除服务
    lease-expiration-duration-in-seconds: 90